config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create]
  
  resources :items, only: [:create, :destroy, :edit, :update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  
  validates :purchase_date, presence: true
  validates :name, presence: true, length: { maximum: 255 }
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def count_items(user)
    return user.items.count
  end
  
  def sum_prices(user)
    return user.items.sum(:price)
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy, :edit]

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:success] = '購入品を登録しました。'
      redirect_to root_url
    else
      @pagy, @items = pagy(current_user.items.order(id: :desc))
      @count_items = count_items(current_user)
      @sum_prices = sum_prices(current_user)
      flash.now[:danger] = '購入品の登録に失敗しました。'
      render 'toppages/index'
    end
  end

  def destroy
    @item.destroy
    flash[:success] = 'レコードを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      flash[:success] = '購入品情報は正常に更新されました。'
      redirect_to root_url
    else
      flash.now[:danger] = '購入品情報は更新できませんでした。'
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:purchase_date, :name, :price)
  end

  def correct_user
    @item = current_user.items.find_by(id: params[:id])
    unless @item
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @item = current_user.items.build  # form_with 用
      @pagy, @items = pagy(current_user.items.order(purchase_date: :desc))
      @count_items = count_items(current_user)
      @sum_prices = sum_prices(current_user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/items/_items.html.erb
<% if items.any? %>
    <div>
      <p class="fs-2">購入品数：<%= count_items %></p>
      <p class="fs-2">購入総額：<%= sum_prices %></p>
    </div>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>購入日</th>
          <th>品目名</th>
          <th>金額</th>
          <th>編集</th>
          <th>削除</th>
        </tr>
      </thead>
      <tbody>
        <% items.each do |item| %>
          <tr>
            <td><%= item.purchase_date %></td>
            <td><%= item.name %></td>
            <td><%= item.price %></td>
            <% if current_user == item.user %>
              <td><%= link_to "Edit", edit_item_path(item), class: 'btn btn-warning btn-sm' %></td>
              <td><%= link_to "Delete", item, method: :delete, data: { confirm: "削除しますか？" }, class: 'btn btn-danger btn-sm' %></td>
            <% end %>
          </tr>
          <% end %>
      </tbody>
    </table>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/items/edit.html.erb
<div class="bg-light">
  <h1>編集ページ</h1>
  <%= form_with(model: @item) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <p><label for="item_purchase_date_1i">購入日:</label></p>
    <p><%= f.date_select :purchase_date, use_month_numbers: true, date_separator: '/', class: 'form-control'%></p>
    <p><%= f.label :name,'品目名:' %></p>
    <p><%= f.text_field :name, class: 'form-control'%></p>
    <p><%= f.label :price,'金額:' %></p>
    <p><%= f.number_field :price, class: 'form-control'%></p>
    <%= f.submit '更新' %>
  <% end %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">Top</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
          <div class="btn-group">
            <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li class="dropdown-item"><%= link_to 'User Profile', user_path(current_user), class: 'nav-link' %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
            </ul>
          </div>
        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>購入品メモアプリ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-sm-4 bg-light">
      <%= form_with(model: @item) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="mb-3">
          <h2>購入品新規登録</h2>
          <div class="mt-4">
            <label for="item_purchase_date_1i">購入日:</label>
            <%= f.date_select :purchase_date, use_month_numbers: true, date_separator: '/', class: 'form-control'%>
          </div>
          <div class="mt-4">
            <%= f.label :name,'品目名:' %>
            <%= f.text_field :name, class: 'form-control'%>
          </div>
          <div class="mt-4">
            <%= f.label :price,'金額:' %>
            <%= f.number_field :price, class: 'form-control'%>
          </div>
        </div>
        <%= f.submit '登録', class: 'btn btn-primary w-100' %>
      <% end %>
    </aside>
    <div class="col-sm-8">
      <%= render 'items/items', items: @items, count_items: @count_items, sum_prices: @sum_prices %>
    </div>
  </div>
<% else %>
  <div class="bg-secondary p-3 p-sm-5 my-4 rounded">
    <div class="text-center text-white">
      <h1>購入品メモアプリ</h1>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<ul class="list-group">
  <li class="list-group-item">ユーザ名：<%= @user.name %></li>
  <li class="list-group-item">メールアドレス：<%= @user.email %></li>
  <li class="list-group-item">登録日：<%= @user.created_at %></li>
</ul>